# Generated by Django 3.2.9 on 2021-11-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
